language: ruby
sudo: required
cache: bundler
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.6.1
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp config/redis.yml.sample config/redis.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
    #  - cp config/devise.yml.sample config/devise.yml
  - cp config/database.yml.sample config/database.yml
  - cp config/blacklight.yml.sample config/blacklight.yml
  - cp config/secrets.yml.sample config/secrets.yml
    #- cp config/ldap.yml.sample config/ldap.yml
  - bundle exec rake db:create
script:
  - bundle exec rubocop
  - bundle exec rake db:migrate
    #- bundle exec rake travis
addons:
  apt:
    packages:
     - imagemagick
services:
  - redis-server
notifications:
  email: tlille01@tufts.edu
