language: ruby
rvm:
  - 2.6.1

sudo: required
dist: trusty
cache: bundler

notifications:
  email:
    - travis.lilleberg@tufts.edu

jdk:
  - oraclejdk8

before_install:
#- gem update --system
- gem install bundler

before_script:
  - cp config/redis.yml.sample config/redis.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/database.yml.sample config/database.yml
  - cp config/blacklight.yml.sample config/blacklight.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/ldap.yml.sample config/ldap.yml
  - cp config/java.yml.sample config/java.yml
  - cp config/tufts_export.yml.sample config/tufts_export.yml
  - bundle exec rake db:create
    # - sudo apt-get -y install libxml2-dev

script:
  #- bundle exec rubocop
  - bundle exec rake db:migrate
  - bundle exec rake travis

addons:
  apt:
    packages:
     - imagemagick
     - libreoffice

services:
  - redis-server
