language: ruby
rvm:
  - 2.6.1

sudo: required
dist: xenial
cache: bundler

notifications:
  email:
    - travis.lilleberg@tufts.edu

jdk:
  - openjdk8

before_install:
#- gem update --system
- gem install bundler
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  # - export PATH=$PATH:/usr/lib/chromium-browser/
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3 # give xvfb some time to start
  - cp config/redis.yml.sample config/redis.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/database.yml.sample config/database.yml
  - cp config/blacklight.yml.sample config/blacklight.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/ldap.yml.sample config/ldap.yml
  - cp config/java.yml.sample config/java.yml
  - cp config/tufts_export.yml.sample config/tufts_export.yml
  - bundle exec sidekiq -d -l /tmp/sidekiq.log
  - bundle exec rake db:create
    # - sudo apt-get -y install libxml2-dev

script:
  #- bundle exec rubocop
  - bundle exec rake db:migrate
  - bundle exec rake travis

addons:
  chrome: stable
  apt:
    packages:
     - imagemagick
     - libreoffice

services:
  - redis-server
  - mysql
  - xvfb
