language: ruby
rvm:
  - 2.6.1

sudo: required
dist: xenial
cache: bundler

notifications:
  email:
    - travis.lilleberg@tufts.edu

jdk:
  - openjdk8

before_install:
- gem install bundler

before_script:
  - cp config/redis.yml.sample config/redis.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/database.yml.sample config/database.yml
  - cp config/blacklight.yml.sample config/blacklight.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/ldap.yml.sample config/ldap.yml
  - cp config/java.yml.sample config/java.yml
  - cp config/tufts.yml.sample config/tufts.yml
  - bundle exec sidekiq -d -l /tmp/sidekiq.log
  - bundle exec rake db:create

script:
  - bundle exec rake db:migrate
  - bundle exec rake travis SPEC_OPTS="--tag ~noci"

addons:
  chrome: stable
  apt:
    packages:
     - imagemagick
     - libreoffice

services:
  - redis-server
  - mysql
