development:
  archivist:
    - archivist1@example.com
  admin:
    - tlille01@tufts.edu
    - tlille01
    - mkorcy01
    - mkorcy01@tufts.edu

stage:
  archivist:
    - archivist1@example.com
    - tlille01


test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  archivist:
    - archivist1@example.com
